baseURL = "http://michaelnet.biz/"
enableEmoji = true
googleAnalytics = "UA-60902806-4"
languageCode = "en-us"
theme = "fortpolio"
title = "Michael E. Nelson"
resume = ""
cv = ""
publishDir = "public"
# TODO: consume GitHub API
githubUsername = ""
enableRobotsTXT = "true"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Resume"
  url = "/michael-e-nelson-resume.pdf"
  weight = 2
