baseURL = "http://michaelnet.biz/"
enableEmoji = true
googleAnalytics = "UA-60902806-4"
languageCode = "en-us"
theme = "fortpolio"
title = "Michael E. Nelson"
resume = ""
cv = ""
publishDir = "docs"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

#[[menu.main]]
#  name = "CV"
#  url = "/michael-e-nelson-resume-9-mar-2017.pdf"
#  weight = 2

[[menu.main]]
  name = "Resume"
  url = "/michael-e-nelson-resume-9-mar-2017.pdf"
  weight = 3
