baseURL = "http://michaelnet.biz/"
enableEmoji = true
googleAnalytics = "UA-60902806-4"
languageCode = "en-us"
theme = "fortpolio"
title = "Michael E. Nelson"
resume = ""
cv = ""
publishDir = "public"
# TODO: consume GitHub API
githubUsername = ""
enableRobotsTXT = "true"
SectionPagesMenu = "main"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Resume"
  url = "/michael-e-nelson-resume.pdf"
  weight = 2

[deployment]
[[deployment.targets]]
name = "michaelnetbiz"
URL = "s3://michaelnet.biz?region=us-east-1"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
#  Cache static assets for 1 year.
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
