name = "Fortpolio"
license = "MIT"
licenselink = "https://github.com/michaelnetbiz/Fortpolio/blob/master/LICENSE"
description = ""
homepage = "http://michaelnet.biz/"
tags = []
features = []
min_version = 0.29

[author]
  name = "Michael E. Nelson"
  homepage = "http://michaelnet.biz/"
